# Generated by Django 5.2.7 on 2026-08-22 13:28

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIDocumentationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ui', 'UI Guide'), ('api', 'API Docs'), ('general', 'General Info')], default='general', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
