# Generated by Django 5.2.7 on 2025-10-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_members_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='firstName',
        ),
    ]
