# Generated by Django 5.2.7 on 2025-10-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_firstname_member_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
